### ISSUE TITLE
Regression from original

### ISSUE THREAD

**Issue by Chris-toe-pher** [yformer/EfficientSAM#10]
I've tested your torchscript models on linux with A6000 gpu.

Regression 1:
Running the original sam huge model, I get 3 output masks from a point prompt, but efficient-sam only outputs 1 mask.

Regression 2:
The original sam offers 2 stage inference using SamPredictor.setimage and SamPredictor.predict but efficient-sam has only 1 stage of inference.

Speed:
Original sam (huge) inference stage 1 - about 450ms, stage 2 - 25ms. This means interactive segmentation adjusting points/boxes can be done at 40fps.
Efficient sam (small) inference one stage - about 105ms. Overall 4-5 times faster but now rather blocky for interactive picking.
Efficient sam tiny - about 75ms. Mask quality not so great.

I haven't looked into the mask quality much and whether I should be comparing one of the smaller sam models. I'd be interested to know your thoughts/plans. Thanks for the work.

**Comment by sulaimanvesal** [comment]
@Chris-toe-pher did you also check the inference time on CPU? what input size you tested out the models?

**Comment by Chris-toe-pher** [comment]
I was using standard HD inputs 1920x1080. Sam resized everything to 1024x1024 internally, I didn't experiment with resizing yet. Of course it can be hard to compare if you change all these things, apples and pears are both tasty.

**Comment by yformer** [comment]
@Chris-toe-pher, 

1, EfficientSAM also outputs 3 masks. The mask with max predicted iou will be used as the final input. @klightz can you link it to your colab code?
2, Our code is based on our internal infra, which makes some changes for efficient training purpose. @bala can you share more context here? We are thinking if we can change it back for 2-stage inference. 
3, For EfficientSAM, we include all the preprocess and the postprocess for the final throughput. @klightz can you share more context here?

**Comment by klightz** [comment]
Actually our head implementation is same as SAM, which means we also get 3 masks at output, we are doing a post processing to take the mask with largest predicted IoU as the final output. Additionally, there are some image reshape operator in the torchscript which will further slow the speed if you directly profiling the whole torchscript. In SAM, it is implemented when setting the image.
