### ISSUE TITLE
Multiple run-time errors

### ISSUE THREAD

**Issue by colinator** [yformer/EfficientSAM#13]
The "Box segmentatoin" section doesn't work at all. There are multiple run-time errors.

**Comment by yformer** [comment]
@colinator, can you follow the colab example or the demo script for box segmentation, https://huggingface.co/spaces/yunyangx/EfficientSAM/blob/main/app.py ?

**Comment by colinator** [comment]
Yes, the app script works. The ipython notebook does not.

**Comment by yformer** [comment]
@klightz can you check why the notebook is not working?

**Comment by colinator** [comment]
You should start by merging this guy's PR: https://github.com/yformer/EfficientSAM/pull/8. Then he's also right about the tuple indexing error...

**Comment by yformer** [comment]
@colinator, Our notebook has fixed those issues. Does it work for you now?
