### ISSUE TITLE
How do you generate masked tokens?

### ISSUE THREAD

**Issue by lianjinke** [yformer/EfficientSAM#21]
Hi author,
When you do pretraining, how do you generate masked tokens? Initiated by random?

**Comment by yformer** [comment]
Hi @lianjinke, the masked tokens generation is the same as MAE. Yes, it is initialized by random.

**Comment by lianjinke** [comment]
Hi @yformer 
Thanks for your reply. So you use a standard MAE to do pretrain? If not, what is the difference between yours and Kaiming He's?

**Comment by yformer** [comment]
Hi @lianjinke, we did not use a standard MAE to pretrain. We propose a SAM-leveraged masked image pretraining, SAMI, which learns to reconstruct features from SAM image encoder. More detail can be seen in [the paper](https://arxiv.org/pdf/2312.00863.pdf)

**Comment by lianjinke** [comment]
Hi @yformer 
Yes, I see the paper, it is straightforward. So why it is *cross* attention decoder? Looks it is pretty similar with the standard MAE which is self attention decoder I think.

**Comment by yformer** [comment]
@lianjinke We found there is no need to put all tokens for decoder for reconstruction. After encoder, the unmasked tokens are learned well.
