### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by ccy610** [yformer/EfficientSAM#25]
Hello author, 
when running the sample_inference.py you provided the day before yesterday, it can run on the CPU but shows insufficient graphics memory when placed on the GPU. May I ask why this is happening? Additionally, I would like to ask if it is possible to directly call the 
build_efficient_sam if I want to make fine-tuning on my own dataset?

**Comment by balakv504** [comment]
Thanks @ccy610. I will take a look. What GPU are you using and how much memory does it have?

**Comment by balakv504** [comment]
For your second question: Yes you can certainly finetune it on your own dataset.

**Comment by ccy610** [comment]
[error.log](https://github.com/yformer/EfficientSAM/files/13673058/error.log)
Thank you very much for your reply，
I am using an RTX 3090, and I did not make any other modifications to the code. I only set the device to cuda. I am just a beginner in the field of artificial intelligence and do not fully understand why the CPU can run but the GPU cannot.

**Comment by balakv504** [comment]
Thanks. Is this happening with the VIT-tiny or VIT-small (I am guessing latter?). Do you have other applications running on the GPU at that time?
If you still have issues, can you try with the following change for that line:
(q @ k.transpose(-2, -1)) * self.scale to
attn = (q[:,:,:,None,:] * k[:,:,None,:,:]).sum(-1) * self.scale

**Comment by ccy610** [comment]
As you said, perhaps there were other software running at the time and the problem had already been resolved. I am really appreciated for your answer.
