### ISSUE TITLE
models for other devices

### ISSUE THREAD

**Issue by AmitIsraeli** [yformer/EfficientSAM#4]
Hi Amazing work,
can you upload jit models for Mac ("mps") and cpu?
It will be awesome thank you (:

**Comment by yformer** [comment]
@AmitIsraeli, Thanks for your interest in this work! Models for CPU are available at the file folder of [Hugging Face Space](https://huggingface.co/spaces/yunyangx/EfficientSAM/).

**Comment by ryouchinsa** [comment]
HI @AmitIsraeli, 

Our C++ code corresponded to Efficient SAM models.
Here is the [Segment Anything CPP Wrapper for macOS](https://github.com/ryouchinsa/sam-cpp-macos/tree/master).

Please let us know your opinion.

![sam](https://github.com/yformer/EfficientSAM/assets/1954306/e8281965-3385-49fe-8a4c-e309c4cdebb1)
