### ISSUE TITLE
the efficientSAM model do not support input  bounding box-prompt?

### ISSUE THREAD

**Issue by duxuan11** [yformer/EfficientSAM#40]
the efficientSAM model do not support input  multi-bounding box?

**Comment by duxuan11** [comment]
`python
def main():
    image = np.array(Image.open("C:\\Users\\ASUS\\Desktop\\avatarget\\datasets\\res\\PCO\\4x\\000003069_PCO_4x.jpg"))
    input_image = image.transpose(2, 0, 1)[None].astype(np.float32) / 255.0
    # batch_size, num_queries, num_points, 2
    input_points = np.array([[[[928, 1700], [1400, 2048]],[[928, 500], [1400, 800]]]], dtype=np.float32)
    # batch_size, num_queries, num_points
    input_labels = np.array([[[2,3],[2,3]]], dtype=np.float32)
    print(input_points.shape)
    print(input_labels.shape)
   #(1, 2, 2, 2)
   #(1, 2, 2)
    predict_onnx(input_image, input_points, input_labels)`

**Comment by Siwakonrome** [comment]
Do you have any example of input bounding box-prompt for Onnx model?
