### ISSUE TITLE
different in jit to pt model

### ISSUE THREAD

**Issue by Whatsetsthisend** [yformer/EfficientSAM#42]
Why do I find that the JIT model provided initially performs significantly better than the current PT model or the converted ONNX model during testing? Additionally, I noticed three nodes in the JIT model that are missing in the PT models.

**Comment by balakv504** [comment]
Hi @Whatsetsthisend 
We just confirmed that the original torchscript and the model in the current repo produces the same outputs and has identical evals on LVIS and COCO. Let us know if you see any descrepancies. An example would be great.

**Comment by yformer** [comment]
@Whatsetsthisend, we checked that the outputs are the same. I close this.
