### ISSUE TITLE
Expected data type and value range of the input images

### ISSUE THREAD

**Issue by carlosuc3m** [yformer/EfficientSAM#44]
Hello I was wondering what is the expected value range for the input tensors. It seems that it is float32, [0,1], but asking just in case.

Thanks a lot for your help.
Regards,
CArlos

**Comment by yformer** [comment]
@carlosuc3m, Yes, it is floa32 and [0, 1] range.

**Comment by carlosuc3m** [comment]
A couple of questions more.

In order to process an uint8 image with a pixel value range from 15 to 150, should the conversion to float32 [0, 1] range be done using the entire range allowed by uint8 images (255), or between the min and max values of the image?

Also for one channel images, should the original one channel image be triplicated for every channel or should the other two channels just be blank?

regards again,
Carlos
