### ISSUE TITLE
How to inspect the intermediate output of the model?

### ISSUE THREAD

**Issue by MrPeterJin** [yformer/EfficientSAM#5]
Hi, firstly very appreciate your work. However, I noticed that the jit encapsulation made it impossible for me to inspect the intermediate output (e.g. encoder feature, decoder feature). Is there any possibility for you to release the model code?

**Comment by MrPeterJin** [comment]
> @MrPeterJin, thanks for your interest in this work! Yeah, the jit model does not generate intermediate output. We will try to release the full code. Due to some parts of our code based on internal infra, it may take a while to publish the full code. When the code is ready, we will message you here.

Thanks! It will be nice to provide batch infer/feature saving APIs for the research development.

**Comment by yformer** [comment]
@MrPeterJin, we released model code with checkpoints. This can help you inspect the intermediate output of the model. Let me know if this works for you.

**Comment by MrPeterJin** [comment]
> @MrPeterJin, we released model code with checkpoints. This can help you inspect the intermediate output of the model. Let me know if this works for you.

Thanks!
