### ISSUE TITLE
CoreML

### ISSUE THREAD

**Issue by FerusAndBeyond** [yformer/EfficientSAM#52]
Would it be possible to export this model to CoreML? In my attempt I got:

 `ValueError: Torch var fusion_type.1 not found in context`

**Comment by yformer** [comment]
@FerusAndBeyond It should be possible to export this model to CoreML. Does this[one] (https://github.com/apple/coremltools/issues/1355) help solve the above error?

**Comment by FerusAndBeyond** [comment]
@yformer I used EdgeSAM instead.
