### ISSUE TITLE
NameError: name 'img_tensor' is not defined

### ISSUE THREAD

**Issue by MuhammadBilal848** [yformer/EfficientSAM#6]
Getting this error while passing the image to Box Segmentation. 
Note: I ran every cell above it.

![image](https://github.com/yformer/EfficientSAM/assets/57318407/ade64899-3711-4a0e-b0f0-036d410f6d7e)

**Comment by yformer** [comment]
@SoTosorrow made some fix. @MuhammadBilal848, we will check the issue and fix it.

**Comment by colinator** [comment]
And then, "mask_ours" is the wrong dim. I suggest something like 

`mask_ours = np.expand_dims(mask_ours, axis=0)`
