### ISSUE TITLE
Consider hosting model files in repo itself

### ISSUE THREAD

**Issue by srinify** [yformer/EfficientSAM#7]
Congrats on the release of the EfficientSAM models! I noticed the files were hosted in Dropbox and created a quick fork to host in GitHub itself (using the XetData extension):

https://github.com/xetdata/EfficientSAM

This lets you work with the models locally, keep them in the Git repo, and just push up to GitHub without having to upload in separate place. I'd love to work with y'all to do the same with this repo too if you're interested!

**Comment by yformer** [comment]
@gabrielgrant Yes, they are available at the file folder of [Hugging Face Space](https://huggingface.co/spaces/yunyangx/EfficientSAM/).
